import type { Metadata } from "next";
import "./globals.css";
import { notoSansKr, jetBrainsMono, gowunBatang } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSansKr.variable} ${jetBrainsMono.variable} ${gowunBatang.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-card px-4 lg:px-0">
        <main className="mx-auto w-full max-w-4xl my-15 border border-border bg-bg rounded-3xl">{children}</main>
      </body>
    </html >
  );
}
